meeting_types:
  - id: office-hours
    name: "Office hours"
    description: "Meet with me about a course you're enrolled in this term."

  - id: chat-check-in
    name: "Chat or check-in"
    description: "Chat or check in with me about some aspect of your research or anything else you'd like to talk with me about."
    instructions: "Please share a Google Doc with your agenda and supporting materials before our meeting."

  - id: project-meeting
    name: "Project meeting"
    description: "Discuss or provide an update on a lab project."
    instructions: "Please share a Google Doc with your agenda and supporting materials before our meeting."

  - id: other
    name: "Other"
    description: "For non-standard meetings. Please specify details in the booking form."
